apiVersion: v1
kind: Pod
metadata:
  name: probe
  labels:
    name: probe
spec:
  containers:
  - name: probe
    image: ghcr.io/eficode-academy/network-multitool
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
