apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "my-secret-pw"
    ports:
      - containerPort: 3306
    volumeMounts:
      - mountPath: /var/lib/mysql
        name: my-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-pvc
